export const DEFAULT_IGNORE_PATTERNS = [
  'node_modules',
  '.git',
  '.expo',
  '.expo-shared',
  '.next',
  '.nuxt',
  '.svelte-kit',
  '.vercel',
  'dist',
  'build',
  'target',
  'vendor',
  'bin',
  'obj',
  'coverage',
  'out',
  '.cache',
  '.vscode',
  '.idea',
  '*.log',
  '*.lock',
  'package-lock.json',
  'yarn.lock',
  'pnpm-lock.yaml',
  'bun.lockb',
  'Cargo.lock',
  'poetry.lock',
  'Gemfile.lock',
  'composer.lock',
  '.DS_Store',
  'Thumbs.db',
  '*.min.js',
  '*.min.css',
  '*.map',
  '*.pyc',
  '__pycache__',
  '*.ico',
  '*.jpg',
  '*.jpeg',
  '*.png',
  '*.gif',
  '*.svg',
  '*.webp',
  '*.eot',
  '*.ttf',
  '*.woff',
  '*.woff2',
  '*.mp4',
  '*.zip',
  '*.tar.gz',
  '*.pdf'
];

export const LLM_CONTEXT_LIMITS = [
  { label: '1M (Gemini 1.5 Pro / 2.0 Flash - Default)', value: 1000000 },
  { label: '200K (Claude 3.5 Sonnet / Opus)', value: 200000 },
  { label: '128K (GPT-4o / GPT-4o-mini)', value: 128000 },
  { label: '32K (GPT-4)', value: 32000 },
  { label: 'Auto (No Limit)', value: 0 }
];

export const NON_CODE_EXTENSIONS = new Set([
  '.md', '.txt', '.rst', '.svg', '.png', '.jpg', '.jpeg', '.gif',
  '.pdf', '.doc', '.docx', '.css', '.scss', '.sass', '.less',
  '.json', '.yaml', '.yml', '.toml', '.xml', '.env', '.example',
  '.lock', '.map', '.html'
]);
